version: '3.4'
services:
  envoy:
    image: 'envoyproxy/envoy-dev:b055dd082c0a49525a97cea6604ac1323a55d2fb'
    volumes:
      - './envoy_config.yaml:/etc/envoy/envoy.yaml'
    ports:
      - '10000:10000'
      - '10001:10001'
    networks:
      - mockingbird-internal
  mockingbird-server:
    image: 'andrewchen20/mockingbird:latest'
    ports:
      - '4000:4000'
      - '3000:3000'
    networks:
      - mockingbird-internal
networks:
  mockingbird-internal:
    name: mockingbird-internal
